version: "3.3"

services:
  app:
    build: .
    volumes:
      - .:/djangoproject
    ports:
      - 8000:8000
      - 9000:9000
    image: mytaxi
    container_name: mytaxi
    entrypoint: /djangoproject/docker-entrypoint.sh

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    depends_on:
      - app
