# Generated by Django 4.1.6 on 2023-02-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_license_img',
            field=models.CharField(max_length=1000000),
        ),
    ]
