# Generated by Django 4.1.6 on 2023-02-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='place_name',
            new_name='address',
        ),
    ]
