# Generated by Django 4.1.6 on 2023-03-07 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_license_img_back',
            field=models.ImageField(blank=True, null=True, upload_to='driver-license/back', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_img_front',
            field=models.ImageField(blank=True, null=True, upload_to='driver-license/front', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
