# Generated by Django 4.1.6 on 2023-03-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_driver_driver_license_img'),
        ('rides', '0002_initial'),
    ]

    operations = [
    ]
