# Generated by Django 4.1.6 on 2023-03-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
