# Generated by Django 4.1.6 on 2023-03-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_driverlocation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='isDriverVerified',
        ),
        migrations.AddField(
            model_name='driver',
            name='statusDriver',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('activated', 'Activated'), ('failed', 'Failed'), ('verified', 'Verified')], max_length=20),
        ),
    ]
