# Generated by Django 4.1.6 on 2023-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_driver_driver_license_img_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_ownership',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented')], max_length=20),
        ),
    ]
