# Generated by Django 4.1.6 on 2023-03-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_remove_driver_isdriververified_driver_statusdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='statusDriver',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('activated', 'Activated'), ('failed', 'Failed'), ('verified', 'Verified')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_ownership',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented')], max_length=20, null=True),
        ),
    ]
