# Generated by Django 4.1.6 on 2023-03-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentid',
            old_name='id_number',
            new_name='matricNo',
        ),
    ]
