# Generated by Django 4.1.6 on 2023-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dialCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
