# Generated by Django 4.1.6 on 2023-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='matricNo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
