# Generated by Django 4.1.6 on 2023-02-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_studentid_remove_student_user_user_isverified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
