# Generated by Django 4.1.6 on 2023-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentid',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
